# Base-image
FROM ruby:3.3.12-slim-trixie@sha256:47b93492bc6afc708dc4f2478c7f1867725c64b3bf43b94ea1bad2dac0314f02 AS base

ARG ATOM_RUBY_VERSION=4.0.7
ARG DEBIAN_REPO
ARG GITHUB_RAW_URL=https://raw.githubusercontent.com
ARG GITHUB_URL=https://github.com
ARG JAVA_VERSION=21.0.12-tem
ARG NODE_24
ARG NODE_VERSION=${NODE_24}
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG NVM
ARG NVM_VERSION=${NVM:-v0.40.8}
ARG PIP_CONFIG
ARG RUBY_LANG_URL
ARG RUBYGEMS_REPO
ARG SDKMAN_URL=https://api.sdkman.io/2

ENV ATOM_CMD=/usr/local/bin/atom \
    ATOM_RUBY_VERSION=$ATOM_RUBY_VERSION \
    BUNDLE_SILENCE_ROOT_WARNING=true \
    JAVA_HOME="/opt/java/${JAVA_VERSION}" \
    JAVA_VERSION=$JAVA_VERSION \
    NVM_DIR="/root/.nvm" \
    PYTHONPATH=/opt/pypi
ENV PATH=${PATH}:/usr/local/bin:/root/.local/bin:/root/.rbenv/bin:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin

COPY ci/images/debian/install.sh /tmp/

COPY ci/images/common/mirrors.sh /tmp/common/mirrors.sh

RUN set -e; \
    . /tmp/common/mirrors.sh; \
    mirrors_on; \
    apt-get update \
 && apt-get install -qq -y --no-install-recommends \
      bash \
      bzip2 \
      curl \
      gawk \
      git-core \
      make \
      unzip \
      zip \
 && apt-get install -qq -y \
      build-essential \
      libffi-dev \
      libmagic-dev \
      libyaml-dev \
      locales \
      python3 \
      python3-dev \
      python3-pip \
 && chmod +x /tmp/install.sh \
 && /tmp/install.sh \
 && rm /tmp/install.sh \
 && pip install \
      --no-cache-dir \
      --target ${PYTHONPATH} \
      --upgrade \
        atom-tools \
 && node -v \
 && npm -v \
 && gem install \
      bundler \
      cocoapods \
 && apt-get purge -y --auto-remove \
      -o APT::AutoRemove::RecommendsImportant=false \
 && rm -rf /var/lib/apt/lists/* /tmp/common \
    && mirrors_off

CMD ["/bin/bash"]


# cdxgen-builder-image
FROM base AS cdxgen-builder

ARG DEBIAN_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG
ARG RUBYGEMS_REPO

ENV NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"

COPY . /opt/cdxgen
COPY ci/images/common/ /tmp/common/

RUN sh /tmp/common/cdxgen-build.sh

# cdxgen-image
FROM base AS cdxgen

ARG ATOM_RUBY_VERSION=4.0.7
ENV ATOM_RUBY_HOME=/root/.rbenv/versions/${ATOM_RUBY_VERSION} \
    CDXGEN_GEM_HOME="/tmp/gems" \
    CDXGEN_IN_CONTAINER=true \
    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin

COPY --from=cdxgen-builder /opt/cdxgen /opt/cdxgen
COPY --from=cdxgen-builder /opt/cdxgen-node-cache /opt/cdxgen-node-cache

RUN set -e; \
    rm -rf ${CDXGEN_GEM_HOME} \
 && mkdir -p ${CDXGEN_GEM_HOME} \
 && chmod a-w -R /opt

WORKDIR /app

ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
