# Base-image
FROM golang:1.26.8-bookworm@sha256:dc9ad6c05acc7a88e5b71bde60a5fe3bd4b9f0db209011711b464107438a8107 AS base

ARG DEBIAN_REPO
ARG GITHUB_RAW_URL=https://raw.githubusercontent.com
ARG GITHUB_URL=https://github.com
ARG NODE_26
ARG NODE_VERSION=${NODE_26}
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG NVM
ARG NVM_VERSION=${NVM:-v0.40.8}
ARG PIP_CONFIG

ENV SKIP_ATOM="yes" \
    NVM_DIR="/root/.nvm" \
    PYTHONPATH=/opt/pypi
ENV PATH=${PATH}:/usr/local/bin:/root/.local/bin:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin

COPY ci/images/debian/install.sh /tmp/

COPY ci/images/common/mirrors.sh /tmp/common/mirrors.sh

RUN set -e; \
    . /tmp/common/mirrors.sh; \
    mirrors_on; \
    apt-get update \
 && apt-get install -qq -y --no-install-recommends \
      bash \
      bzip2 \
      curl \
      gawk \
      git-core \
      make \
      unzip \
      zip \
 && apt-get install -qq -y \
      build-essential \
      locales \
      python3 \
      python3-dev \
      python3-pip \
 && chmod +x /tmp/install.sh \
 && /tmp/install.sh \
 && rm /tmp/install.sh \
 && pip install \
      --no-cache-dir \
      --target ${PYTHONPATH} \
      --upgrade \
        blint \
 && node -v \
 && npm -v \
 && apt-get purge -y --auto-remove \
      -o APT::AutoRemove::RecommendsImportant=false \
 && rm -rf /var/lib/apt/lists/* /tmp/common \
    && mirrors_off

CMD ["/bin/bash"]


# cdxgen-builder-image
FROM base AS cdxgen-builder

ARG DEBIAN_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG

ENV NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"
ENV CDXGEN_INSTALL_NO_OPTIONAL=true

COPY . /opt/cdxgen
COPY ci/images/common/ /tmp/common/

RUN sh /tmp/common/cdxgen-build.sh

# cdxgen-image
FROM base AS cdxgen

ENV CDXGEN_IN_CONTAINER=true \
    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin

COPY --from=cdxgen-builder /opt/cdxgen /opt/cdxgen
COPY --from=cdxgen-builder /opt/cdxgen-node-cache /opt/cdxgen-node-cache

RUN chmod a-w -R /opt

WORKDIR /app

ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
