# Base-image
FROM php:8.3.35-bookworm@sha256:c24b55afdf860c874b9ec6267ced132ff52de97d308ab08e6cf41e8596e509f7 AS base

ARG COMPOSER_URL=https://getcomposer.org
ARG DEBIAN_REPO
ARG GITHUB_RAW_URL=https://raw.githubusercontent.com
ARG GITHUB_URL=https://github.com
ARG JAVA_VERSION=21.0.12-tem
ARG NODE_24
ARG NODE_VERSION=${NODE_24}
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG NVM
ARG NVM_VERSION=${NVM:-v0.40.8}
ARG PIP_CONFIG
ARG SDKMAN_URL=https://api.sdkman.io/2

ENV JAVA_HOME="/opt/java/${JAVA_VERSION}" \
    JAVA_VERSION=$JAVA_VERSION \
    NVM_DIR="/root/.nvm" \
    PYTHONPATH=/opt/pypi
ENV PATH=${PATH}:/usr/local/bin:/root/.local/bin:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin
        
COPY ci/images/debian/install.sh /tmp/

COPY ci/images/common/mirrors.sh /tmp/common/mirrors.sh

RUN set -e; \
    . /tmp/common/mirrors.sh; \
    mirrors_on; \
    apt-get update \
 && apt-get install -qq -y --no-install-recommends \
      bash \
      bzip2 \
      curl \
      gawk \
      git-core \
      make \
      unzip \
      zip \
 && apt-get install -qq -y \
      build-essential \
      libcurl4-openssl-dev \
      libicu-dev \
      libonig-dev \
      libxml2-dev \
      libzip-dev \
      locales \
      python3 \
      python3-dev \
      python3-pip \
 && docker-php-ext-install \
      curl \
      intl \
      mbstring \
      mysqli \
      pdo \
      pdo_mysql \
      xml \
      zip \
 && curl -L $COMPOSER_URL/installer \
      | sed "s|\$uriScheme.'://getcomposer.org'|'$COMPOSER_URL'|g" \
      | php \
          -- \
          --install-dir=/usr/local/bin \
          --filename=composer \
 && chmod +x /tmp/install.sh \
 && /tmp/install.sh \
 && rm /tmp/install.sh \
 && pip install \
      --no-cache-dir \
      --target ${PYTHONPATH} \
      --upgrade \
        atom-tools \
 && node -v \
 && npm -v \
 && php -v \
 && composer --version \
 && apt-get purge -y --auto-remove \
      -o APT::AutoRemove::RecommendsImportant=false \
 && rm -rf /var/lib/apt/lists/* /tmp/common \
    && mirrors_off

CMD ["/bin/bash"]


# cdxgen-builder-image
FROM base AS cdxgen-builder

ARG DEBIAN_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG

ENV NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"
ENV CDXGEN_SMOKE_TESTS="phpastgen --help && atom-tools --help"

COPY . /opt/cdxgen
COPY ci/images/common/ /tmp/common/

RUN sh /tmp/common/cdxgen-build.sh

# cdxgen-image
FROM base AS cdxgen

ENV CDXGEN_IN_CONTAINER=true \
    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin

COPY --from=cdxgen-builder /opt/cdxgen /opt/cdxgen
COPY --from=cdxgen-builder /opt/cdxgen-node-cache /opt/cdxgen-node-cache

RUN chmod a-w -R /opt

WORKDIR /app

ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
