minimumReleaseAge: '4320'
minimumReleaseAgeExclude:
- '@cdxgen/*'
- '@appthreat/*'
trustPolicy: no-downgrade
blockExoticSubdeps: true
lockfileIncludeTarballUrl: true
strictDepBuilds: true
preferSymlinkedExecutables: false
optimisticRepeatInstall: true
cleanupUnusedCatalogs: true