blockExoticSubdeps: true
cleanupUnusedCatalogs: true
lockfileIncludeTarballUrl: true
minimumReleaseAge: '4320'
minimumReleaseAgeExclude:
  - '@cdxgen/*'
  - 'pnpm'
  - '@pnpm/*'
  - '@appthreat/*'
  - 'typescript'
  - '@typescript/*'
optimisticRepeatInstall: true
preferSymlinkedExecutables: false
strictDepBuilds: true
trustPolicy: no-downgrade
