/**
 * Checks if the provided language is a Rust language alias.
 *
 * @param {string} language The language to check.
 * @returns {boolean} True if the language is Rust.
 */
export function isRusiRustLanguage(language: string): boolean;
/**
 * Reads and parses the JSON output generated by rusi.
 *
 * @param {string} jsonFile Path to the rusi output file.
 * @returns {Object|undefined} Parsed JSON report or undefined.
 */
export function readRusiJsonFile(jsonFile: string): Object | undefined;
/**
 * Invokes the rusi binary to analyze a codebase.
 *
 * @param {string} src Directory to analyze.
 * @param {string} outputFile Path to store the resulting JSON file.
 * @param {Object} options Options containing rusi configurations.
 * @returns {boolean} True if successful.
 */
export function runRusiAnalysis(src: string, outputFile: string, options?: Object): boolean;
/**
 * Orchestrates the execution of rusi and returns the parsed report.
 *
 * @param {string} src Directory to analyze.
 * @param {Object} options Configuration options.
 * @returns {Object|undefined} Parsed rusi report or undefined.
 */
export function analyzeRusiProject(src: string, options?: Object): Object | undefined;
/**
 * Extracts and maps CycloneDX evidence structures from a rusi report.
 *
 * @param {Object} rusiReport The parsed JSON generated by rusi.
 * @param {Array} components The components present in the SBOM.
 * @returns {Object} Maps representing evidence structures.
 */
export function collectRusiEvidence(rusiReport?: Object, components?: any[]): Object;
//# sourceMappingURL=rusi.d.ts.map