# Base-image
FROM ruby:3.4.11-alpine@sha256:50133d02799e7da49a1e0bd16d865701622fd61d150a8cd3463edf0016504af5 AS base

ARG ALPINE_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG
ARG RUBYGEMS_REPO

ENV PATH=${PATH}:/usr/local/bin \
    PYTHONPATH=/opt/pypi

COPY ci/images/common/mirrors.sh /tmp/common/mirrors.sh

RUN set -e; \
    . /tmp/common/mirrors.sh; \
    mirrors_on; \
    apk update \
 && apk add --no-cache \
      bash \
      build-base \
      bzip2 \
      curl \
      gcc \
      git \
      g++ \
      make \
      musl-dev \
      nodejs \
      npm \
      openjdk21 \
      python3 \
      python3-dev \
      py3-pip \
      py3-virtualenv \
      ruby-dev \
      tar \
 && npm install -g corepack \
 && /usr/bin/python --version \
 && /usr/bin/python -m pip install \
      --no-cache-dir \
      --target ${PYTHONPATH} \
      --upgrade \
        atom-tools \
 && node -v \
 && npm -v \
 && java -version \
 && python3 --version \
 && gem install \
      bundler \
      cocoapods \
 && rm -rf /var/cache/apk/* /tmp/common \
    && mirrors_off


# cdxgen-builder-image
FROM base AS cdxgen-builder

ARG ALPINE_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG
ARG RUBYGEMS_REPO

ENV NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"
ENV CDXGEN_SMOKE_TESTS="rbastgen --help && atom-tools --help"

COPY . /opt/cdxgen
COPY ci/images/common/ /tmp/common/

RUN sh /tmp/common/cdxgen-build.sh

# cdxgen-image
FROM base AS cdxgen

ENV CDXGEN_GEM_HOME="/tmp/gems" \
    CDXGEN_IN_CONTAINER=true \
    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin

COPY --from=cdxgen-builder /opt/cdxgen /opt/cdxgen
COPY --from=cdxgen-builder /opt/cdxgen-node-cache /opt/cdxgen-node-cache

RUN set -e; \
    rm -rf ${CDXGEN_GEM_HOME} \
 && mkdir -p ${CDXGEN_GEM_HOME} \
 && chmod a-w -R /opt

WORKDIR /app

ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
