# Base-image
FROM php:8.3.35-alpine@sha256:8dbeb51c352cf1f70d5d50f3642c9fbed311e914475ea2382f5bc1525bef7bb3 AS base

ARG ALPINE_REPO
ARG COMPOSER_URL=https://getcomposer.org
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG

ENV PATH=${PATH}:/usr/local/bin \
    PYTHONPATH=/opt/pypi

COPY ci/images/common/mirrors.sh /tmp/common/mirrors.sh

RUN set -e; \
    . /tmp/common/mirrors.sh; \
    mirrors_on; \
    apk update \
 && apk add --no-cache \
      autoconf \
      bash \
      bzip2 \
      curl \
      curl-dev \
      gcc \
      git \
      g++ \
      icu-dev \
      libxml2-dev \
      libzip-dev \
      make \
      musl-dev \
      nodejs \
      npm \
      oniguruma-dev \
      openjdk21 \
      pkgconf \
      python3 \
      python3-dev \
      py3-pip \
      py3-virtualenv \
      re2c \
 && npm install -g corepack \
 && /usr/bin/python --version \
 && /usr/bin/python -m pip install \
      --no-cache-dir \
      --target ${PYTHONPATH} \
      --upgrade \
        atom-tools \
 && docker-php-ext-install \
      curl \
      intl \
      mbstring \
      mysqli \
      pdo \
      pdo_mysql \
      xml \
      zip \
 && curl -L $COMPOSER_URL/installer \
      | sed "s|\$uriScheme.'://getcomposer.org'|'$COMPOSER_URL'|g" \
      | php \
          -- \
          --install-dir=/usr/local/bin \
          --filename=composer \
 && node -v \
 && npm -v \
 && php -v \
 && composer --version \
 && rm -rf /var/cache/apk/* /tmp/common \
    && mirrors_off


# cdxgen-builder-image
FROM base AS cdxgen-builder

ARG ALPINE_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG

ENV NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"
ENV CDXGEN_SMOKE_TESTS="phpastgen --help && atom-tools --help"

COPY . /opt/cdxgen
COPY ci/images/common/ /tmp/common/

RUN sh /tmp/common/cdxgen-build.sh

# cdxgen-image
FROM base AS cdxgen

ENV CDXGEN_IN_CONTAINER=true \
    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin

COPY --from=cdxgen-builder /opt/cdxgen /opt/cdxgen
COPY --from=cdxgen-builder /opt/cdxgen-node-cache /opt/cdxgen-node-cache

RUN chmod a-w -R /opt

WORKDIR /app

ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
