# Base-image
FROM python:3.14.8-alpine@sha256:f6a589d43c42b9e7f7dc67a12d37132491f362859a5d750607710cc56da3bc72 AS base

ARG ALPINE_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG

ENV CFLAGS="-fcommon" \
    PATH=${PATH}:/usr/local/bin

COPY ci/images/common/mirrors.sh /tmp/common/mirrors.sh

RUN set -e; \
    . /tmp/common/mirrors.sh; \
    mirrors_on; \
    apk update \
 && apk add --no-cache \
      build-base \
      cyrus-sasl-dev \
      krb5-dev \
      libffi-dev \
      libxml2-dev \
      libxslt-dev \
      nodejs \
      npm \
      openldap-dev \
      openssl-dev \
      postgresql-dev \
      sqlite-dev \
      xz-dev \
 && npm install -g corepack \
 && python --version \
 && python -m pip install \
      --break-system-packages \
      --no-cache-dir \
      --target ${PYTHONPATH} \
      --upgrade \
        atom-tools \
 && node -v \
 && npm -v \
 && rm -rf /var/cache/apk/* /tmp/common \
    && mirrors_off


# cdxgen-builder-image
FROM base AS cdxgen-builder

ARG ALPINE_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG

ENV NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"

COPY . /opt/cdxgen
COPY ci/images/common/ /tmp/common/

RUN sh /tmp/common/cdxgen-build.sh

# cdxgen-image
FROM base AS cdxgen

ENV CDXGEN_IN_CONTAINER=true \
    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
    PATH=${PATH}:/opt/cdxgen/node_modules/.bin

COPY --from=cdxgen-builder /opt/cdxgen /opt/cdxgen
COPY --from=cdxgen-builder /opt/cdxgen-node-cache /opt/cdxgen-node-cache

RUN chmod a-w -R /opt

WORKDIR /app

ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
