import { Buffer } from "node:buffer";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import process from "node:process";

import { assert, describe, it } from "poku";

import {
  localCargoMetadataEnabled,
  readCargoCacheMetadata,
  resetCargoCacheState,
} from "./cargoCache.js";
import { getCratesMetadata } from "./ecosystems.js";

const REGISTRY = "index.crates.io-1949cf8c6b5b557f";

/**
 * Build a throwaway Cargo home rather than commit one.
 *
 * The index cache is a binary file under a `.cache/` directory, which the
 * repo's .gitignore excludes — a committed fixture would be silently absent
 * on a fresh clone and these tests would pass against nothing. Writing it here
 * also documents the envelope the reader parses: a version byte, the index
 * format version, then NUL-separated fields holding the registry revision and
 * alternating version strings and JSON blobs.
 *
 * @returns {string} Path to the Cargo home.
 */
function buildCargoHome() {
  const home = mkdtempSync(join(tmpdir(), "cdxgen-cargo-home-"));
  const srcDir = join(home, "registry", "src", REGISTRY, "demo-crate-1.2.3");
  mkdirSync(srcDir, { recursive: true });
  writeFileSync(
    join(srcDir, "Cargo.toml"),
    [
      "# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO",
      "[package]",
      'edition = "2021"',
      'rust-version = "1.70"',
      'name = "demo-crate"',
      'version = "1.2.3"',
      'description = "A crate used to exercise the local registry reader"',
      'license = "MIT OR Apache-2.0"',
      'repository = "https://github.com/example/demo-crate"',
      'homepage = "https://demo-crate.example"',
      "",
      "[features]",
      'default = ["std"]',
      "std = []",
      "",
    ].join("\n"),
    "utf-8",
  );

  const cacheRoot = join(home, "registry", "index", REGISTRY, ".cache");
  writeIndexCache(join(cacheRoot, "de", "mo"), "demo-crate", [
    [
      "1.0.0",
      {
        cksum: "11".repeat(32),
        features: {},
        yanked: false,
        pubtime: "2023-01-05T10:00:00Z",
      },
    ],
    [
      "1.2.3",
      {
        cksum: "22".repeat(32),
        features: { default: ["std"], std: [] },
        yanked: false,
        pubtime: "2024-02-09T12:30:00Z",
        rust_version: "1.70",
      },
    ],
    [
      "1.3.0",
      {
        cksum: "33".repeat(32),
        features: {},
        yanked: true,
        pubtime: "2024-06-01T09:00:00Z",
      },
    ],
  ]);
  // A crate the index knows but Cargo never extracted. Three-character names
  // bucket under `3/<first letter>/`.
  writeIndexCache(join(cacheRoot, "3", "i"), "idx", [
    [
      "9.9.9",
      {
        cksum: "44".repeat(32),
        features: {},
        yanked: false,
        pubtime: "2022-03-03T03:03:03Z",
      },
    ],
  ]);
  return home;
}

/**
 * Write one crate's index cache file in Cargo's binary envelope.
 *
 * @param {string} dir Directory the file belongs in.
 * @param {string} name Crate name, which is also the file name.
 * @param {Array<[string, Object]>} rows Version and its index entry, in
 *   publish order.
 * @returns {void}
 */
function writeIndexCache(dir, name, rows) {
  mkdirSync(dir, { recursive: true });
  const parts = [
    Buffer.from([0x03, 0x02, 0x00, 0x00, 0x00]),
    Buffer.from('etag: "deadbeef"\u0000', "utf-8"),
  ];
  for (const [vers, entry] of rows) {
    parts.push(
      Buffer.from(
        `${vers}\u0000${JSON.stringify({ name, vers, deps: [], ...entry })}\u0000`,
        "utf-8",
      ),
    );
  }
  writeFileSync(join(dir, name), Buffer.concat(parts));
}

const FIXTURE_HOME = buildCargoHome();
process.on("exit", () => {
  rmSync(FIXTURE_HOME, { force: true, recursive: true });
});

/**
 * The reader is exercised against a fixture Cargo home rather than the
 * machine's own `~/.cargo`, so the assertions hold on a build agent that has
 * never run cargo.
 *
 * Tests are awaited: they share the module's memoized registry and index
 * state, which `resetCargoCacheState` clears between them.
 */
async function withCargoHome(home, fn) {
  const previous = process.env.CARGO_HOME;
  process.env.CARGO_HOME = home;
  resetCargoCacheState();
  try {
    return await fn();
  } finally {
    if (previous === undefined) {
      delete process.env.CARGO_HOME;
    } else {
      process.env.CARGO_HOME = previous;
    }
    resetCargoCacheState();
  }
}

await describe("readCargoCacheMetadata", async () => {
  await it("merges the extracted manifest with the sparse index entry", async () => {
    await withCargoHome(FIXTURE_HOME, async () => {
      const meta = await readCargoCacheMetadata("demo-crate", "1.2.3");
      assert.ok(meta, "the fixture crate must be found");
      // From src/<registry>/<name>-<version>/Cargo.toml
      assert.strictEqual(meta.license, "MIT OR Apache-2.0");
      assert.strictEqual(
        meta.description,
        "A crate used to exercise the local registry reader",
      );
      assert.strictEqual(
        meta.repository,
        "https://github.com/example/demo-crate",
      );
      assert.strictEqual(meta.homepage, "https://demo-crate.example");
      assert.strictEqual(meta.rustVersion, "1.70");
      // From index/<registry>/.cache/de/mo/demo-crate
      assert.strictEqual(meta.checksum, "22".repeat(32));
      assert.strictEqual(meta.yanked, false);
      assert.strictEqual(meta.publishTime, "2024-02-09T12:30:00Z");
      assert.deepStrictEqual(meta.features, { default: ["std"], std: [] });
      // Both files answered.
      assert.strictEqual(meta.sources.length, 2);
    });
  });

  await it("reports the newest version that was not yanked", async () => {
    await withCargoHome(FIXTURE_HOME, async () => {
      // 1.3.0 is newer but yanked, so 1.2.3 is what the registry calls newest.
      const meta = await readCargoCacheMetadata("demo-crate", "1.2.3");
      assert.strictEqual(meta.latestVersion, "1.2.3");
    });
  });

  await it("marks a yanked version as yanked", async () => {
    await withCargoHome(FIXTURE_HOME, async () => {
      const meta = await readCargoCacheMetadata("demo-crate", "1.3.0");
      assert.strictEqual(meta.yanked, true);
      // Only the index knows this version; it was never extracted.
      assert.strictEqual(meta.license, undefined);
      assert.strictEqual(meta.sources.length, 1);
    });
  });

  await it("answers from the index alone for a crate that was never built", async () => {
    await withCargoHome(FIXTURE_HOME, async () => {
      // A three-character name buckets under `3/<first letter>/`.
      const meta = await readCargoCacheMetadata("idx", "9.9.9");
      assert.ok(meta, "index-only crates must still be found");
      assert.strictEqual(meta.checksum, "44".repeat(32));
      // Without a license the caller must fall back to the registry.
      assert.strictEqual(meta.license, undefined);
    });
  });

  await it("returns nothing for a crate the local registry does not have", async () => {
    await withCargoHome(FIXTURE_HOME, async () => {
      assert.strictEqual(
        await readCargoCacheMetadata("not-a-real-crate", "1.0.0"),
        undefined,
      );
      assert.strictEqual(
        await readCargoCacheMetadata("demo-crate", "42.0.0"),
        undefined,
      );
    });
  });

  await it("returns nothing when there is no Cargo home at all", async () => {
    await withCargoHome(
      join(tmpdir(), "cdxgen-cargo-home-absent"),
      async () => {
      assert.strictEqual(
        await readCargoCacheMetadata("demo-crate", "1.2.3"),
        undefined,
      );
    });
  });

  await it("rejects missing names and versions without touching the disk", async () => {
    await withCargoHome(FIXTURE_HOME, async () => {
      assert.strictEqual(await readCargoCacheMetadata("", "1.2.3"), undefined);
      assert.strictEqual(await readCargoCacheMetadata("demo-crate", ""), undefined);
    });
  });
});

await describe("localCargoMetadataEnabled", async () => {
  await it("is on by default and off when the registry is demanded", () => {
    const previous = process.env.CARGO_METADATA_SOURCE;
    try {
      delete process.env.CARGO_METADATA_SOURCE;
      assert.strictEqual(localCargoMetadataEnabled(), true);
      process.env.CARGO_METADATA_SOURCE = "registry";
      assert.strictEqual(localCargoMetadataEnabled(), false);
      process.env.CARGO_METADATA_SOURCE = "REGISTRY";
      assert.strictEqual(localCargoMetadataEnabled(), false);
      process.env.CARGO_METADATA_SOURCE = "local";
      assert.strictEqual(localCargoMetadataEnabled(), true);
    } finally {
      if (previous === undefined) {
        delete process.env.CARGO_METADATA_SOURCE;
      } else {
        process.env.CARGO_METADATA_SOURCE = previous;
      }
    }
  });
});

await describe("getCratesMetadata with a populated Cargo home", async () => {
  await it("serves a cached crate without reaching crates.io", async () => {
    // RUST_CRATES_URL points at a port nothing is listening on: any request
    // fails, so a crate that comes back enriched can only have been answered
    // locally. Prefetching is disabled so the batch pool does not intervene.
    const previousUrl = process.env.RUST_CRATES_URL;
    const previousPrefetch = process.env.CDXGEN_NO_PREFETCH;
    const previousHome = process.env.CARGO_HOME;
    process.env.RUST_CRATES_URL = "http://127.0.0.1:1/api/v1/crates/";
    process.env.CDXGEN_NO_PREFETCH = "true";
    process.env.CARGO_HOME = FIXTURE_HOME;
    resetCargoCacheState();
    try {
      const [cached, uncached] = await getCratesMetadata([
        { name: "demo-crate", version: "1.2.3" },
        { name: "idx", version: "9.9.9" },
      ]);

      assert.strictEqual(cached.license, "MIT OR Apache-2.0");
      assert.strictEqual(
        cached.description,
        "A crate used to exercise the local registry reader",
      );
      const props = Object.fromEntries(
        (cached.properties || []).map((prop) => [prop.name, prop.value]),
      );
      assert.strictEqual(props["cdx:cargo:metadataSource"], "local-registry");
      assert.strictEqual(props["cdx:cargo:yanked"], "false");
      assert.strictEqual(props["cdx:cargo:latest_version"], "1.2.3");
      assert.strictEqual(props["cdx:cargo:rust_version"], "1.70");

      // The index-only crate has no license locally, so it took the network
      // path — which failed against the dead port and left it unenriched.
      assert.strictEqual(uncached.license, undefined);
      assert.ok(
        !(uncached.properties || []).some(
          (prop) => prop.name === "cdx:cargo:metadataSource",
        ),
        "a crate that fell through to the registry must not claim a local source",
      );
    } finally {
      restore("RUST_CRATES_URL", previousUrl);
      restore("CDXGEN_NO_PREFETCH", previousPrefetch);
      restore("CARGO_HOME", previousHome);
      resetCargoCacheState();
    }
  });

  await it("takes the registry path when the caller needs publisher provenance", async () => {
    // The predictive audit passes preferLocalCache: false. With the registry
    // unreachable the crate comes back unenriched, which proves the local
    // shortcut was not taken even though the fixture could have served it.
    const previousUrl = process.env.RUST_CRATES_URL;
    const previousPrefetch = process.env.CDXGEN_NO_PREFETCH;
    const previousHome = process.env.CARGO_HOME;
    process.env.RUST_CRATES_URL = "http://127.0.0.1:1/api/v1/crates/";
    process.env.CDXGEN_NO_PREFETCH = "true";
    process.env.CARGO_HOME = FIXTURE_HOME;
    resetCargoCacheState();
    try {
      const [only] = await getCratesMetadata(
        [{ name: "demo-crate", version: "1.2.3" }],
        { preferLocalCache: false },
      );
      assert.strictEqual(only.license, undefined);
    } finally {
      restore("RUST_CRATES_URL", previousUrl);
      restore("CDXGEN_NO_PREFETCH", previousPrefetch);
      restore("CARGO_HOME", previousHome);
      resetCargoCacheState();
    }
  });
});

function restore(key, value) {
  if (value === undefined) {
    delete process.env[key];
  } else {
    process.env[key] = value;
  }
}
