name: Prepare runner for repotests
description: Run all actions needed to prepare a worker for repo-testing.

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
    - name: Use Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: .nvmrc
    - name: Install dependencies
      shell: bash
      run: |
        pnpm install:frozen
        mkdir -p $OUTPUT_DIR
