name: Check dependency usage

on:
  pull_request:
    paths:
      - 'pnpm-lock.yaml'

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  check-dependency:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413  # v6.1.0
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false
      - name: Build
        run: |
          pnpm i --no-frozen-lockfile
      - name: Comment
        run: |
          read -a array <<< "${PR_TITLE}"
          if [ "${array[2]}" == "dependency" ]; then
            node bin/cdxgen.js --exclude test/\*\* -t js --deep
            echo "Output of \`pnpm why ${array[3]}\`:" > _tree.txt
            echo "\`\`\`" >> _tree.txt
            pnpm why ${array[3]} >> _tree.txt
            echo "\`\`\`" >> _tree.txt
            echo "Output of \`jq\` on components:" >> _tree.txt
            echo "\`\`\`" >> _tree.txt
            jq --arg dep "${array[3]}@" '.components[] | select(."bom-ref" | test($dep)) | { group, name, version, purl, licenses }' bom.json >> _tree.txt
            echo "\`\`\`" >> _tree.txt
            echo "Output of \`jq\` on dependencies:" >> _tree.txt
            echo "\`\`\`" >> _tree.txt
            jq --arg dep "${array[3]}@" '.dependencies[] | select(.ref | test($dep))' bom.json >> _tree.txt
            jq --arg dep "${array[3]}@" '.dependencies[] | select(.dependsOn | any(test($dep)))' bom.json >> _tree.txt
            echo "\`\`\`" >> _tree.txt
          fi
        env:
          FETCH_LICENSE: true
          PR_TITLE: ${{ github.event.pull_request.title }}
      - uses: mshick/add-pr-comment@ec328af66588ab8f77cdeb2c264f14aba45bbf59  # v3.12.0
        if: hashFiles('_tree.txt')
        with:
          message-path: _tree.txt
